context:
  name: fastfetch
  version: "2.40.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}-cli/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: b4bc551ef2ec48cb0a14d21e266d16ea0469d55524b221464df1a7619bb339cc
  patches:
    - if: linux
      then:
        - fix-localip-linux.patch

build:
  number: 0
  skip: win

requirements:
  ignore_run_exports:
    # https://github.com/fastfetch-cli/fastfetch/wiki/Dependencies
    # Fastfetch dynamically loads needed libraries if they are available.
    from_package:
      - chafa
      - glib
      - imagemagick
      - sqlite
      - zlib
      - if: linux
        then:
          - dbus
          - libdrm
          - libxcb
          - ocl-icd
          - wayland
          - xorg-libx11
          - xorg-libxrandr
  run_constraints:
    - ${{ pin_compatible('chafa') }}
    - ${{ pin_compatible('glib') }}
    - ${{ pin_compatible('imagemagick') }}
    - ${{ pin_compatible('sqlite') }}
    - ${{ pin_compatible('zlib') }}
    - if: linux
      then:
        - ${{ pin_compatible('dbus') }}
        - ${{ pin_compatible('libdrm') }}
        - ${{ pin_compatible('libxcb') }}
        - ${{ pin_compatible('ocl-icd') }}
        - ${{ pin_compatible('wayland') }}
        - ${{ pin_compatible('xorg-libx11') }}
        - ${{ pin_compatible('xorg-libxrandr') }}

  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - cmake
    - ninja
    # used in cmake
    - python 3.13.*
  host:
    # https://github.com/fastfetch-cli/fastfetch/wiki/Dependencies
    - chafa
    - glib
    - imagemagick 7.*
    - libvulkan-loader
    - libvulkan-headers
    - sqlite
    - zlib
    - if: linux
      then:
        - dbus
        - libdrm
        - libxcb
        - ocl-icd
        - wayland
        - xorg-libx11
        - xorg-libxrandr
        - ${{ cdt('pciutils-devel') }}
  run: []

tests:
  - script:
      - fastfetch --version
      - fastfetch

about:
  homepage: https://github.com/fastfetch-cli/fastfetch
  summary: Like neofetch, but much faster because written mostly in C
  license: MIT
  license_file: LICENSE
  repository: https://github.com/fastfetch-cli/fastfetch

extra:
  recipe-maintainers:
    - pavelzw
